volumes:
    postgres-data:
        external: true
    pg-admin:
        external: true

services:
  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: planr@email.com
      PGADMIN_DEFAULT_PASSWORD: pass
      PGADMIN_DISABLE_POSTFIX: 1

    postgres:
        build:
            dockerfile: ./Dockerfile.dev
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=pass
        ports:
            - 15432:5432
    
    server:
        build:
            context: ./server
            dockerfile: ./Dockerfile.dev
        ports:
            - "9000:9000"
        volumes:
            -./server:/app
        environment:
            DATABASE_URL: postgresql://server:password@postgres
            WAIT_HOST: postgres:5432

    client:
        image: node:lts-bullseye
        command: /bin/bash run.sh
        working_dir: /app
        volumes:
            - ./client:/app
        ports: 
            -"3000:3000"
        environment:
            HOST_OS: ${OS}
            NODE_ENV: development
            HOST: "0.0.0.0"
            PUBLIC_URL: http://localhost:3000
            REACT_APP_USERS_API_HOST: http://localhost:8000
