version: '3.8'
services:
  db:
    image: postgres:13
    platform: linux/amd64
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_HOST: db
      DB_NAME: postgres
      DB_PASSWORD: password
      DB_PORT: 5432
      PORT: 3000
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
  pgadmin:
    image: dpage/pgadmin4
    platform: linux/amd64
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 'pgadmin4@pgadmin.org'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  postgres_data:
    external: true
  pgadmin_data: {}
